service: class-insights-attendance
#file: noinspection YAMLSchemaValidation,YAMLSchemaValidation,YAMLSchemaValidation,YAMLSchemaValidation
frameworkVersion: "3"
version: 1.0.1
commonData: ${file(../../serverless.common.yml)}

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-bundle
  - serverless-dotenv-plugin

custom:
  dotenv:
    # default: project root
    path: ../../.env

provider:
  name: aws
  runtime: ${self:commonData.serverlessConfiguration.runtime}
  versionFunctions: ${self:commonData.serverlessConfiguration.versionFunctions}
  stage: ${self:commonData.serverlessConfiguration.stage}
  region: ${self:commonData.serverlessConfiguration.region}
  memorySize: ${self:commonData.serverlessConfiguration.environment.stageSpecificData.${self:provider.environment.stage}.defaultMemorySize}
  timeout: ${self:commonData.serverlessConfiguration.timeout}

  environment:
    stage: ${self:commonData.serverlessConfiguration.stage}
    accountRegion: ${self:commonData.serverlessConfiguration.region}
    serviceUrlIdentifier: attendance
    authorizerType: ${self:commonData.serverlessConfiguration.environment.authorizerType}
    authorizerArn: ${self:commonData.serverlessConfiguration.environment.stageSpecificData.${self:provider.environment.stage}.authorizerArn}
    authorizerResultTtlInSeconds: ${self:commonData.serverlessConfiguration.environment.authorizerResultTtlInSeconds}
    authorizerIdentitySource: ${self:commonData.serverlessConfiguration.environment.authorizerIdentitySource}

  tracing:
    apiGateway: true
    lambda: true
  apiGateway:
    metrics: true
  logs:
    http:
      level: ERROR

  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
        - s3:GetObject
        - s3:PutObject
      Resource: "*"

functions:
  takeAttendance:
    handler: handlers/takeAttendance.takeAttendance
    events:
      - http:
          path: ${self:provider.environment.serviceUrlIdentifier}/takeAttendance
          method: post
          cors: true
          authorizer: authorizerFunc #NOTE:-uncomment it for local
          # authorizer:
          #   type: ${self:provider.environment.authorizerType}
          #   arn: ${self:provider.environment.authorizerArn}
          #   resultTtlInSeconds: ${self:provider.environment.authorizerResultTtlInSeconds}
          #   identitySource: ${self:provider.environment.authorizerIdentitySource}
          response:
            headers:
              X-Content-Type-Options: "'nosniff'"
              Access-Control-Allow-Origin: "'*'"
  viewAttendance:
    handler: handlers/viewAttendance.viewAttendance
    events:
      - http:
          path: ${self:provider.environment.serviceUrlIdentifier}/viewAttendance
          method: get
          cors: true
          # authorizer: authorizerFunc #NOTE:-uncomment it for local
          authorizer:
            type: ${self:provider.environment.authorizerType}
            arn: ${self:provider.environment.authorizerArn}
            resultTtlInSeconds: ${self:provider.environment.authorizerResultTtlInSeconds}
            identitySource: ${self:provider.environment.authorizerIdentitySource}
          response:
            headers:
              X-Content-Type-Options: "'nosniff'"
              Access-Control-Allow-Origin: "'*'"

  # authorizerFunc:
  #   handler: ../auth/authHandler/authorizer.main
